version: '3.9'

services:
    postgis:
        image: postgis/postgis
        container_name: postgis_container
        restart: on-failure
        environment: 
            - POSTGRES_DB=property
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data 

  
    app:
        container_name: app_container
        build: .
        command: sh -c "
                    python manage.py makemigrations &&
                    python manage.py migrate --no-input && 
                    python manage.py collectstatic --no-input && 
                    python manage.py initadmin && 
                    gunicorn -k gevent config.wsgi:application -b 0.0.0.0:8000"
        restart: on-failure
        depends_on: 
            - postgis
            - redis
        expose: 
            - "8000"
        networks:
            - main
        volumes: 
            - .:/code/
            - ./static:/app/static
            - ./media:/app/media

        
    nginx:
        container_name: nginx_container
        command: nginx -g 'daemon off;'
        image: nginx
        restart: on-failure
        depends_on:
            - app
        networks: 
            - main
        ports: 
            - "80:80"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./media:/app/media
            - ./static:/app/static
    
    redis:
        image: redis
        container_name: redis_container
        command: >
            --requirepass "admin"
            --maxclients 5
        ports: 
            - "6379:6379"
        networks: 
            - main
        volumes:
        - redisdata:/data
            
            
networks: 
    main:
        external: true
        
volumes: 
    static:
        external: true
        
    postgres_data:
        external: true
        
    redisdata:
        external: true
